file = open("demo.txt",'r')
content = file.read()
print(content)
file.close()
file=open("demo.txt",'w')
file.write("Machine learning")
file.close()
file = open("demo.txt",'r')
content=file.read()
print(content)
file.close()
